name: Deploy-model-tensor

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  

jobs:
  prediction:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: 'echo "field: ${{secrets.MODEL_NAME}}"'

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
        
    - name: Download and run the Docker base image
      run: docker run -d --name serving_base tensorflow/serving

    - name: pip install reqs
      run: pip install -r requirements.txt
      
    - name: run python program 
      run: python linear.py

    - name: update docker user in k8 
      run: sed -i 's/{docker_user}/${{secrets.DOCKER_USER}}/g' manifests/k8s.yaml

    - name: update model name in k8 
      run: sed -i 's/{model_name}/${{secrets.MODEL_NAME}}/g' manifests/k8s.yaml

    - name: update _ by - 
      run: sed -i 's/_/-/g' manifests/k8s.yaml

    - name: update sha in k8
      run: sed -i 's/{github.sha}/${{ github.sha }}/g' manifests/k8s.yaml

    - name: ls -la 
      run: ls -la  
      #cat manifests/k8s.yaml

#    - name: Extract model
#      run: unzip linear_model.zip
      
    - name: copy model to the Docker image
      run: docker cp linear-model "serving_base:/models/linear-model"
      
    - name: Build the custom Docker image
      run: docker commit --change "ENV MODEL_NAME ${{secrets.MODEL_NAME}}" serving_base ${{secrets.DOCKER_USER}}/tensorflow-${{secrets.MODEL_NAME}}:${{ github.sha }}
  
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/tensorflow-${{secrets.MODEL_NAME}}:${{ github.sha }}
      
    - uses: okteto/context@2.7.0
      with:
        token: ${{secrets.OKTETO_TOKEN }}


    - name: Deploy and Wait
      uses: okteto/actions/deploy@v1
      env:
        KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
      with:
        namespace: ${{secrets.OKTETO_NAMESPACE }}
        manifest: manifests/k8s.yaml
        tag: ${{ secrets.DOCKER_USERNAME }}/tensorflow_${{secrets.MODEL_NAME}}:${{ github.sha }}
        #waitOn: adsoftsito/${{secrets.MODEL_NAME}}
         
  #  - name: test python 
  #    run: python linearmodel_client.py
